### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Applications/video_srt_macos.app/Contents/Resources/video-srt.zip' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by huangbqsky** [loongwind/video-srt-mac#1]
Debug service listening on ws://127.0.0.1:52266/yXiq1GPPqeo=/ws
Syncing files to device macOS...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Applications/video_srt_macos.app/Contents/Resources/video-srt.zip' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      new FileHandle (package:archive/src/io/input_file_stream.dart:16:29)
#3      new InputFileStream (package:archive/src/io/input_file_stream.dart:81:17)
#4      ZipRepository.unzip (package:video_srt_macos/repository/zip_repository.dart:10:25)
#5      ZipRepository.unzipVideoSrt (package:video_srt_macos/repository/zip_repository.dart:23:11)
<asynchronous suspension>
#6      _MainViewState.init (package:video_srt_macos/view/main_window.dart:33:5)
<asynchronous suspension>

**Comment by loongwind** [comment]
需要将 video_srt_macos.app 放到应用目录 Applications 下，因为这里获取路径是写死从 /Applications/video_srt_macos.app/下获取的，如果是开发调试的话可以修改一下这个地址
